### ISSUE TITLE
Foundations of Documentation

### ISSUE THREAD

**Issue by Nebrethar** [Nebrethar/Docs-Diversity-Inclusion-Badging#2]
**Describe the issue**
The documentation needs an overhaul; it needs to match the new issue templates.

It needs a README to start!

Self-assigning

**Additional context**
Anyone who would like to help start this project may reach me at <msnell@unomaha.edu>

@SMotaal If you have a chance sometime I need some help structuring the project (this is just the docs). Let me know if you can meet for the subject :)

**Comment by SMotaal** [comment]
@Nebrethar thanks for reaching out… certainly let's figure out when…

My thought it would be organic to do this right before our D&I meeting or after the community meeting slot. I am also available Sunday, maybe other days if we want to hassle with a doodle.

**Comment by Nebrethar** [comment]
@SMotaal I appreciate that you are willing to meet. Sunday would be ideal as I have classes around the other two meetings. Please reach out to me at my email <msnell@unomaha.edu> and we can work out the details!

**Comment by SMotaal** [comment]
@Nebrethar awesome, let me know if/when a time in the proposed window for today works for your.

**Comment by Nebrethar** [comment]
Thanks @SMotaal for helping kickstart this project! I am closing this as we have moved over to Projects.

**Comment by SMotaal** [comment]
https://github.com/Nebrethar/Docs-Diversity-Inclusion-Badging/projects/1
