### ISSUE TITLE
GSoC Idea: Build Workflow Process for CHAOSS Diversity & Inclusion Badging

### ISSUE THREAD

**Issue by Nebrethar** [Nebrethar/Docs-Diversity-Inclusion-Badging#5]
# About the GSoC Project

The CHAOSS Diversity and Inclusion Badging Program began as a way to ensure that D&I metrics can have significant impact in the ways that communities function. The program was created to encourage projects and events towards positive diversity & inclusion practices. The goal of the Diversity & Inclusion Badging Program is to encourage projects and events to obtain D&I badges for reasons of pride, leadership, self-reflection, and self-improvement on issues critical to building the inclusive communities.

The primary goals of the Diversity & Inclusion Badging Program include:

 - Establishing an environment where projects and events can engage in the D&I badging program
 - Aligning the badging program with best practices, guidelines, and recommendations from Diversity & Inclusion efforts on the CHAOSS project
 - Connecting with existing badging standards of IMS Global including building an open peer-review system for the D&I Badging Program.

The aim of this project regards all of these goals, and the work will help the entire Diversity & Inclusion Badging Program. The volunteer for this project will assist in creating a badge submission workflow and peer-review system for the badging process.

* _Difficulty:_ Medium
* _Requirements:_ Extensive experience with GitHub and the GitHub workflow. A willingness to meet new members of the open source community.
* _Recommended:_ Experience in the open source community would be a positive, but it is not required.
* _Mentors:_ Matt Snell, Matt Germonprez, Saleh Abdel Motaal

# Microtasks

To become familiar with the CHAOSS D&I Badging Program, Please take a look at the following documentation:

  - [IMS Standards for Digital Badges](https://www.imsglobal.org/activity/digital-badges) (Emphasis on the Background section at the bottom of the page)
  - [The Journal of Open Source Software Submission Process](https://joss.readthedocs.io/en/latest/)
  - [A quick Overview of the CHAOSS Project](https://chaoss.community/about/)

Once you are more familiar with the related projects, Please complete these microtasks:

Any line marked with a `Q` contains a question you must answer.
Any line marked with an `A` contains an action you must take.

  - Microtask 0
  After reviewing the IMS Standards for Digital Badges and the Journal of Open Source Software Documentation, answer the following questions:
  `Q 0` How would IMS standards be helpful in creating a software badge?
  `Q 1` What parts of the Journal of Open Source Software Documentation could be helpful in improving the D&I Badging Project? (Hint: There are no wrong answers)
  
  - Microtask 1:
  Navigate to [the D&I badging repository](https://github.com/Nebrethar/Docs-Diversity-Inclusion-Badging) and review both the Event and Project folders.
  `Q 2` How do these folders differ from each other?
  `Q 3` How are they similar?

  - Microtask 2:
  Review the issue templates, namely those used for submitting to the project. Clone the repository to your local computer and review the issue templates again.
  `Q 4` Are the issue templates any different when you view them in GitHub versus your local machine? If so, how?
  `Q 5` Explain why this project may want to use GitHub issue templates as a badging submission method.

**Comment by GeorgLink** [comment]
Could you please continue to define microtasks? The goal is to have some deliverable that we expect from students to judge their readiness to dive into the mentorship.

**Comment by Nebrethar** [comment]
@GeorgLink I apologize for not getting to this sooner.  I have created some relevant microtasks. I will be creating more while the project gains content.

**Comment by GeorgLink** [comment]
Thanks @Nebrethar, keep in mind that we want to know whether the potential students have basic knowledge and skills and willingness to learn. It is not about actually achieving anything for CHAOSS.

**Comment by bistaastha** [comment]
Hi @Nebrethar @GeorgLink! I am going through the links under 'Author and Reviewer Guides' in JOSS documentation. Are there any specific parts that should be focused more upon than the others?

**Comment by GeorgLink** [comment]
I'll let @Nebrethar and @SMotaal reply to this since I am not that deeply involved in the project.

**Comment by Nebrethar** [comment]
@bistaastha Just a note, the discussion has been moved but I have provided some recommendations related to your question 👍 

https://github.com/badging/diversity-and-inclusion/issues/1

**Comment by GeorgLink** [comment]
We can close this issue, pr https://github.com/chaoss/governance/pull/157 was merged
